from __future__ import annotations

APP_SCHEMA_VERSION = 28
PROJECT_SCHEMA_VERSION = 2
SETTINGS_SCHEMA_VERSION = 2
RECOVERY_SNAPSHOT_SCHEMA_VERSION = 2

# Compatibility aliases used by earlier phases.
LEGACY_PROJECT_SCHEMA_VERSION = 1
LEGACY_SETTINGS_SCHEMA_VERSION = 1
LEGACY_RECOVERY_SNAPSHOT_SCHEMA_VERSION = 1
